#ifndef __ERRORS_MATRIX_H__

#define __ERRORS_MATRIX_H__

#define EXIT_CANNOT_MATRIX_PRODUCT_COLUMN 30
#define EXIT_INCORRECT_MATRIX_SIZE 31
#define EXIT_INCORRECT_AMOUNT_ROW_ELEMENTS_INPUTTED 32

#endif // #ifndef __ERRORS_MATRIX_H__
