#ifndef __ERRORS_HASH_TABLE_CLOSE_H__

#define __ERRORS_HASH_TABLE_CLOSE_H__

#define EXIT_HASH_TABLE_CLOSE_MALLOC_ERROR 20
#define EXIT_HASH_TABLE_CLOSE_REALLOC_ERROR 21

#endif // #ifndef __ERRORS_HASH_TABLE_CLOSE_H__