#ifndef __ERRORS_LINKED_LIST_STACK_H__

#define __ERRORS_LINKED_LIST_STACK_H__

#define EXIT_ALLOCATING_NODE_ERROR                  20
#define EXIT_EMPTY_LINKED_LIST_STACK_ERROR          21

#endif // #ifndef __ERRORS_LINKED_LIST_STACK_H__
