#ifndef __ERRORS_ADJACENCY_MATRIX_H__

#define __ERRORS_ADJACENCY_MATRIX_H__

#define EXIT_ALLOCATING_ROW_PTRS_MEMORY_ERRORY  10
#define EXIT_ALOCATING_ROW_MEMORY_ERRROR        11

#endif // #ifndef __ERRORS_MATRIX_H__