#ifndef __ERRORS_CONTACT_H__

#define __ERRORS_CONTACT_H__

#define EXIT_STATUS_TYPE_DIFFERS 40
#define EXIT_INCORRECT_SURNAME 41
#define EXIT_INCORRECT_NAME 42
#define EXIT_INCORRECT_STREET 43
#define EXIT_INCORRECT_HOUSE 44
#define EXIT_INCORRECT_STATUS 45
#define EXIT_INCORRECT_POST 46
#define EXIT_INCORRECT_AGENCY 47

#endif // #ifndef __ERRORS_CONTACT_H__