#ifndef __ERRORS_DATE_H__

#define __ERRORS_DATE_H__

#define EXIT_INCORRECT_DATE 20
#define EXIT_DAY_INCORRECT_SYMBOLS 21
#define EXIT_MONTH_INCORRECT_SYMBOLS 22
#define EXIT_YEAR_INCORRECT_SYMBOLS 23

#endif // #ifndef __ERRORS_DATE_H__