#ifndef __ERRORS_HASH_TABLE_OPEN_H__

#define __ERRORS_HASH_TABLE_OPEN_H__

#define EXIT_HASH_TABLE_OPEN_MALLOC_ERROR 20
#define EXIT_HASH_TABLE_OPEN_REALLOC_ERROR 21

#endif // #ifndef __ERRORS_HASH_TABLE_OPEN_H__