#ifndef __ERRORS_LINKED_LIST_QUEUE_H__

#define __ERRORS_LINKED_LIST_QUEUE_H__

#define EXIT_LINKED_LIST_QUEUE_OVERFLOW     10
#define EXIT_LINKED_LIST_QUEUE_EMPTY        11
#define EXIT_LINKED_LIST_QUEUE_MEM_ALLOCATE 12

#endif // #ifndef __ERROR__ERRORS_LINKED_LIST_QUEUE_H__S_QUEUE_H__
